# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon jerardo aguiniga cervantes
open_collective: # Replace with a single Open Collective jerardo aguiniga cervantes
ko_fi: # Replace with a single Ko-fi jerardo aguiniga cervantes
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay jerardo aguiniga cervantes
issuehunt: # Replace with a single IssueHunt jerardo aguiniga cervantes
otechie: # Replace with a single Otechie jerardo aguiniga cervantes
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
jerardoaguinigacervantes6@gmail.com jerardo aguiniga cervantes 01131986 
